version: '3.9' # optional since v1.27.0
services:
  jupyter:
    # image: jupyter/datascience-notebook:python-3.9
    image: jupyter/datascience-notebook:python-3.10
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan
